### ISSUE TITLE
Add automated detection for hard-coded string

### ISSUE THREAD

**Issue by LeoColman** [LeoColman/Petals#120]
As a continuation to #119, we should have a setup to find if we have forgotten any unlocalized string in the code.

**Comment by priyatanu** [comment]
Hi @LeoColman ,
can i take up this task. Would like to contribute and I am interested in this project

**Comment by LeoColman** [comment]
Absolutely!
Let me assign it to you :)

**Comment by priyatanu** [comment]
> Absolutely! Let me assign it to you :)

But i am having an issue building the project - 
e: org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during IR lowering
File being compiled: /Users/Priyatanu.Dey/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/MainActivity.kt
The root cause java.lang.RuntimeException was thrown at: org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.generate(FunctionCodegen.kt:51)
	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException(CodegenUtil.kt:253)

**Comment by LeoColman** [comment]
Replaced by #600
